# Generated by Django 3.1.5 on 2021-01-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide_addis_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos')),
                ('number_of_seats', models.IntegerField()),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide_addis_bot.telegramuser')),
            ],
        ),
    ]
